App\Entity\Status:
    type: entity
    table: status
    id:
        id:
            type: smallint
            nullable: false
        options:
            unsigned: true
            id: true
        generator:
            strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 32
            options:
              fixed: false
    lifecycleCallbacks: {  }